// Generated by CoffeeScript 1.6.2
var build_rss_list, load_rss_feed, render_item, rss_feed_library, save_to_local;

rss_feed_library = {
  'Techcrunch': 'feeds.feedburner.com/TechCrunch/',
  'AVC': 'http://feeds.feedburner.com/avc',
  'Venturebeat': 'http://venturebeat.com/feed/'
};

load_rss_feed = function(feed) {
  var condition, url;

  if (rss_feed_library[feed]) {
    feed = rss_feed_library[feed];
  }
  condition = escape("select * from xml where url = '" + feed + "'");
  url = "http://query.yahooapis.com/v1/public/yql?q=" + condition + "&format=json&diagnostics=true";
  return $.get(url, function(data) {
    save_to_local(feed, data.query.results.rss);
    return build_rss_list(data.query.results.rss);
  });
};

save_to_local = function(feed, rss) {
  var items, key, node, _i, _len, _ref;

  key = md5(feed);
  items = window.localStorage[key];
  if (!items) {
    items = {};
  } else {
    items = JSON.parse(items);
  }
  _ref = rss.channel.item;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    node = _ref[_i];
    key = md5(node.link);
    items[key] = node;
  }
  return window.localStorage[key] = JSON.stringify(items);
};

render_item = function(item) {
  var model;

  model = "<div onclick=\"load_item_content('{{id}}')\" class=\"node-item\">\n	<div class=\"title\">{{title}}</div>\n	<div class=\"description\">{{description}}</div>\n</div>";
  model = model.replace("{{title}}", item.title);
  model = model.replace("{{description}}", item.description);
  return model = model.replace("{{id}}", md5(item.link));
};

build_rss_list = function(rss) {
  var inner_html, node, _i, _len, _ref;

  inner_html = '';
  _ref = rss.channel.item;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    node = _ref[_i];
    inner_html += render_item(node);
  }
  return $('#item-list').html(inner_html);
};
